### ISSUE TITLE
Characters show up not in order

### ISSUE THREAD

**Issue by lethefrost** [chairfull/GodotRichTextLabel2#10]
Hi! Thank you for making this awesome addon! 

When I run the demo, I get the following effects in the video:

https://github.com/user-attachments/assets/381d3558-64a8-4fd1-907b-9d50bd5667b3

it seems that the characters are not showing up in one-by-one order like in your demonstration videos. Is that some intended behavior newly in the later version? or is it just some bug or related to specific platform or device (for example could this be due to a race condition caused by concurrency? haven't read through the source code yet) Can anyone reproduce this? 

though I have to say this effect looks pretty cool and I kinda like it 😂 If possible, I hope to ensure consistent effect running on any device.

**Comment by chairfull** [comment]
You can change the `animation` property to one of 11 different animation effects. That one is `prickle`. Set it to `fader` to have it just fade them in one-by-one.
