### ISSUE TITLE
Godot's built-in bbcode effects do not clear in parsing

### ISSUE THREAD

**Issue by dog-on-moon** [chairfull/GodotRichTextLabel2#13]
From what I can tell, Godot's BBCode effects do not fully clear:

```
[shake]Text that does not[] fully clear.
```

leads to the entire string being shaky:

![image](https://github.com/user-attachments/assets/cff26522-8896-4ce3-84b8-46f221e5c24f)

**Comment by chairfull** [comment]
Fixed for `shake` and effects listed here: https://docs.godotengine.org/en/stable/tutorials/ui/bbcode_in_richtextlabel.html
