### ISSUE TITLE
Name Change Proposal

### ISSUE THREAD

**Issue by ThePat02** [chairfull/GodotRichTextLabel2#2]
This is a really nice and fleshed out addition, as the default `RichTextLabel` can be quite cumbersome to work with. However, the name is something you should reconsider. Hear me out:

If you create a normal `RichTextLabel` and start to duplicate it / add another one, Godot will automatically add numbers to the names in the SceneTree, which can result into confusing mix-ups with your improved version.

My suggestions for new names:

- RicherTextLabel
- ImprovedRichTextLabel
- FancyTextLabel

Thank you for your great work ^^

**Comment by chairfull** [comment]
Good idea, thanks. Changed it.
