### ISSUE TITLE
Lag when selecting RicherTextLabel node and emoji error

### ISSUE THREAD

**Issue by thoarodynzun** [chairfull/GodotRichTextLabel2#3]
Hey this add-on is terrific I am just having 2 issues and I was wondering if you know why. Everytime I select my RicherTextLabel node in the inspector godot freezes for a couple of seconds.

The second issue I have is when using effects with emojis they are not displayed and I get this error  : 
res://addons/richtext2/RicherTextLabel.gd:758 - Invalid access to property or key 'emoji_font' on a base object of type 'Dictionary'.

thanks in advance!

**Comment by chairfull** [comment]
First problem may be fixed now. I noticed Godot calls `_get_properties()` for every `@export`, so I moved all exports to _get_properties(). And cached some things that may have held it up.

For the second problem, with `emoji_font` I added some tests. Be sure there is a font somewhere in your project with `emoji` in it's name. And then you may need to clear the `font_cache` on any old labels. (In future I'll make a more eloquent solution.)

(Also please create a separate issue for each unique problem.)
