### ISSUE TITLE
Can we control these effects with animation player?

### ISSUE THREAD

**Issue by hardikbhalodi** [chairfull/GodotRichTextLabel2#4]
I want to control the effect with animation player let say character by character fade up with Animation player timeline. so i can seek animation player and also play it reverse.  is it possible?

**Comment by chairfull** [comment]
The `RichTextAnimation` has a `progress` float you could adjust with an `AnimationPlayer` but you will have to set `_play = false` and maybe `player_on_bbcode = false`.

But there may be problems when using them with the `[wait][pace][hold][skip]`.

Is there something specific you want to do? I was thinking of making a `RichTextAnimationPlayer` for bigger fancier animations used in cinematics and such. But I don't know when I will get to that.

**Comment by hardikbhalodi** [comment]
Thank you for response, 

you did great work. I wanted to control the Text Animation specially the character by character or word by word animation using Animation Player for Cinematic effects, so i can play reverse animation and the character animation also be reverse. with just RichTextEffect it is not possible.  if you make RichTextAnimationPlayer which can use the track to animate the characters or any other way to do with existing Animation Player would be great.
