### ISSUE TITLE
Abnormal text effect after export

### ISSUE THREAD

**Issue by aiaimimi0920** [chairfull/GodotRichTextLabel2#6]
in editor：
![image](https://github.com/user-attachments/assets/26231bd3-de78-47ec-8672-38da0f6f7a16)

in export exe：
![image](https://github.com/user-attachments/assets/da15f28c-280b-4623-90cb-fb844358804e)

this is bbcode = 
1. [sin;rainbow freq=1.0 sat=0.8 val=0.8]testtesttesttesttesttesttesttesttesttesttesttesttesttesttest[]
2. [sin]testtesttesttesttesttesttesttesttesttesttesttesttesttesttest[]
3. [rain]testtesttesttesttesttesttesttesttesttesttesttesttesttesttest[]

I am using Windows export with godot 4.4 dev2

**Comment by chairfull** [comment]
Fixed by checking for `.gdc` files.

(Had same error on Linux and it fixed, so this should work for Windows too.)

**Comment by aiaimimi0920** [comment]
@chairfull 
Thank you for your help. I can indeed see the text effect in the exported version now

But I think there is something bad hidden in your update:

1. File name change, variable name modification: I think such destructive modifications are acceptable, but it is better to make fewer such modifications and preferably increase the version number by a large one

2. Godot 4.3 is not compatible, you introduced Dictionary [StringName, Variant]. However, this feature is the latest addition, https://godotengine.org/article/dev-snapshot-godot-4-4-dev-2/#typed -Dictionaries. 
It is actually only supported on the unstable version 4.4, so users need to update the engine to version 4.4 in order to use this plugin properly.

Anyway, thank you for updating
