### ISSUE TITLE
"horizontal_alignment" attribute does not exist in godot4.3

### ISSUE THREAD

**Issue by aiaimimi0920** [chairfull/GodotRichTextLabel2#8]
@chairfull 
“horizontal_alignment” This attribute was introduced in the latest godot4.4 dev1.
https://github.com/godotengine/godot/commit/94ad663c0f8dfd56a7643f45a609266dd4c2293b#diff-7b1a5fbe91ef12896027c6ffa2727efc80e2228f5633f48258615b907441db95R6021

But it does not exist in Godot 4.3.
So the current code cannot run in godot4.3

I'm not sure if I need to report this issue to you. If the plugin itself is developed for Godot 4.4, then this issue doesn't need to be modified.

**Comment by chairfull** [comment]
Okay, reverted back. I was wondering how I didn't notice the feature till now.
