### ISSUE TITLE
bbcode or color problem

### ISSUE THREAD

**Issue by aiaimimi0920** [chairfull/GodotRichTextLabel2#9]
I'm not very good at describing this issue,

I have provided a demo, you can watch the code and click the button

[test_richer_text_label.zip](https://github.com/user-attachments/files/17080015/test_richer_text_label.zip)

According to this code
```
%RicherTextLabel2.color = Color.BLACK
%RicherTextLabel2.bbcode = "《幸运21》开发中试玩DEMO v0.0.2\n不代表最终质量"
%RicherTextLabel3.color = Color.BLUE
%RicherTextLabel3.bbcode = "《幸运21》开发中试玩DEMO v0.0.2"
```

RicherTextLabel2 should be turned black and centered
RicherTextLabel3 should turn blue

But the actual result is like this：
![image](https://github.com/user-attachments/assets/da86c612-3cd7-4646-b8ef-622eb2e29f03)

**Comment by chairfull** [comment]
Both problems should be fixed now.

**Comment by aiaimimi0920** [comment]
good, Tested everything to be normal and can be used

**Comment by aiaimimi0920** [comment]
@chairfull  It seems that the problem has not been completely solved
1. Set the %RicherTextLabel3 color to green in the editor
2. Call code when clicking button
```
	%RicherTextLabel3.color = Color.YELLOW
	%RicherTextLabel3.bbcode = "《幸运21》开发中试玩DEMO"
```

You can observe that %RicherTextLabel3 did not change color

**Comment by chairfull** [comment]
It's because it was set up not to update if you give it the exact same `bbcode` twice.
I changed it, and rewrote a number of things. Should be more stable now.

**Comment by aiaimimi0920** [comment]
good, Tested everything to be normal and can be used
Thanks your help
